### ISSUE TITLE
libccd-dev is Ubuntu system package in utopic

### ISSUE THREAD

**Issue by scpeters** [ros-gbp/libccd-release#1]
This is a little bit early, but I wanted to report that [libccd-dev is an Ubuntu system package as of utopic](http://packages.ubuntu.com/cs/utopic/libccd-dev) (14.10). We should move towards deprecating the ros version of libccd in favor of the official Ubuntu version.

@j-rivero

**Comment by cottsay** [comment]
FYI this package has been in Fedora since version 17 (current is 22) and is in EPEL 6 and 7.

+1 for moving to the system package

**Comment by scpeters** [comment]
@tfoote will this have to wait for ROS-K?

**Comment by tfoote** [comment]
Yeah, kinetic will be the first one without trusty support as it will be based on Ubuntu X.

**Comment by scpeters** [comment]
I would propose that we not include this as a ros package in K since it is available in Ubuntu X. Do we just need a rosdep rule for it?

**Comment by tfoote** [comment]
Yes creating a rosdep rule for it should be done. Though for clarity it should have a distinct name not try to overload the old dependency, probably `libccd-dev`

**Comment by scpeters** [comment]
It looks like fcl is in Ubuntu W,X as well. @cottsay is fcl in fedora?

**Comment by tfoote** [comment]
There's one in the robotics sig: http://copr-dist-git.fedorainfracloud.org/cgit/@robotics-sig/gazebo-latest/fcl.git/ I don't know if it's upstreamed though

**Comment by scpeters** [comment]
Ok, I just submitted the new rosdep keys: https://github.com/ros/rosdistro/pull/10874

**Comment by scpeters** [comment]
The rosdep keys have been added in https://github.com/ros/rosdistro/pull/10879
